# Generated by Django 6.0.1 on 2026-01-15 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeiro',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.paciente'),
        ),
        migrations.AlterField(
            model_name='financeiro',
            name='descricao',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
