# Generated by Django 6.0.1 on 2026-01-16 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_financeiro_paciente_alter_financeiro_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='data_pagamento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='forma_pagamento',
            field=models.CharField(blank=True, choices=[('pix', 'PIX'), ('cartao', 'Cartão'), ('dinheiro', 'Dinheiro'), ('transferencia', 'Transferência')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='paga',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='financeiro',
            name='consulta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.consulta'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='status',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
