# Generated by Django 6.0.1 on 2026-01-16 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_consulta_data_pagamento_consulta_forma_pagamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='observacoes_clinicas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='paga',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='status',
            field=models.CharField(choices=[('agendada', 'Agendada'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='agendada', max_length=20),
        ),
    ]
