# Generated by Django 6.0.1 on 2026-01-16 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_paciente_observacoes_clinicas_alter_consulta_paga_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
    ]
