# Generated by Django 6.0.1 on 2026-01-17 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_profissional', models.CharField(default='Dra. Priscilla Faria', max_length=100)),
                ('nome_clinica', models.CharField(default='Odontologia', max_length=100)),
            ],
        ),
    ]
