# Generated by Django 6.0.1 on 2026-01-17 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_configuracao'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracao',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
