# Generated by Django 6.0.1 on 2026-01-18 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='clinic',
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='home.clinic'
            ),
        ),
        migrations.AddField(
            model_name='financeiro',
            name='clinic',
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='home.clinic'
            ),
        ),
        migrations.AddField(
            model_name='paciente',
            name='clinic',
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='home.clinic'
            ),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='paga',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='financeiro',
            name='consulta',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='home.consulta'
            ),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cargo',
            field=models.CharField(
                choices=[('admin', 'Admin'), ('recepcao', 'Recepção')],
                default='recepcao',
                max_length=20
            ),
        ),
        migrations.AlterField(
            model_name='profile',
            name='clinic',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='home.clinic'
            ),
        ),
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
