# Generated by Django 6.0.1 on 2026-01-18 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_consulta_clinic_financeiro_clinic_paciente_clinic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinic',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='financeiro',
            name='consulta',
        ),
        migrations.AddField(
            model_name='configuracao',
            name='clinic',
            field=models.OneToOneField(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='home.clinic'
            ),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='cor_primaria',
            field=models.CharField(default='#0d6efd', max_length=20),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='cor_secundaria',
            field=models.CharField(default='#6c757d', max_length=20),
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='nome_clinica',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='nome_profissional',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='clinic',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='home.clinic'
            ),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='forma_pagamento',
            field=models.CharField(
                blank=True,
                choices=[
                    ('dinheiro', 'Dinheiro'),
                    ('pix', 'PIX'),
                    ('debito', 'Débito'),
                    ('credito', 'Crédito'),
                    ('boleto', 'Boleto'),
                    ('transferencia', 'Transferência')
                ],
                max_length=50,
                null=True
            ),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='status',
            field=models.CharField(default='agendada', max_length=20),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='valor',
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='financeiro',
            name='clinic',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='home.clinic'
            ),
        ),
        migrations.AlterField(
            model_name='financeiro',
            name='descricao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='financeiro',
            name='tipo',
            field=models.CharField(
                choices=[('entrada', 'Entrada'), ('saida', 'Saída')], max_length=20),
        ),
        migrations.AlterField(
            model_name='financeiro',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='clinic',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='home.clinic'
            ),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cargo',
            field=models.CharField(
                choices=[
                    ('admin', 'Administrador'),
                    ('dentista', 'Dentista'),
                    ('recepcao', 'Recepção'),
                    ('financeiro', 'Financeiro')
                ],
                default='admin',
                max_length=20
            ),
        ),
    ]
