# Generated by Django 6.0.1 on 2026-01-18 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_remove_clinic_logo_remove_financeiro_consulta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeiro',
            name='consulta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.consulta'),
        ),
    ]
