# Generated by Django 6.0.1 on 2026-01-18 16:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_financeiro_consulta'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='clinic',
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='home.clinic'
            ),
        ),
        migrations.AlterField(
            model_name='financeiro',
            name='clinic',
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='home.clinic'
            ),
        ),
        migrations.AlterField(
            model_name='financeiro',
            name='paciente',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='home.paciente'
            ),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='clinic',
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='home.clinic'
            ),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='data_cadastro',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
