# Generated by Django 6.0.1 on 2026-01-19 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_profile_ativo_alter_consulta_clinic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='google_event_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='google_access_token',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='google_refresh_token',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='google_token_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
