# Generated by Django 6.0.1 on 2026-02-26 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_consulta_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracao',
            name='clinic',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.clinic'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consulta',
            name='clinic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.clinic'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='financeiro',
            name='clinic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.clinic'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='financeiro',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='clinic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.clinic'),
            preserve_default=False,
        ),
    ]
