# Generated by Django 6.0.1 on 2026-02-26 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_paciente_bairro_paciente_cep_paciente_cidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='responsavel',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='responsavel',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Responsável/Tutor'),
        ),
    ]
