# Generated by Django 6.0.1 on 2026-02-26 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_consulta_responsavel_paciente_responsavel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependentes', to='home.paciente', verbose_name='Responsável Cadastrado'),
        ),
    ]
