# Generated by Django 6.0.1 on 2026-02-27 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_paciente_responsavel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracao',
            name='cor_primaria',
        ),
        migrations.RemoveField(
            model_name='configuracao',
            name='cor_secundaria',
        ),
        migrations.AddField(
            model_name='configuracao',
            name='assinatura_digital',
            field=models.ImageField(blank=True, help_text='Upload da imagem da assinatura (preferencialmente PNG transparente)', null=True, upload_to='assinaturas/'),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='cro',
            field=models.CharField(blank=True, help_text='Ex: CRO-SP 123.456', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='documento_fiscal',
            field=models.CharField(blank=True, help_text='CPF ou CNPJ para o recibo', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='nome_clinica',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='nome_profissional',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='paciente',
            unique_together={('clinic', 'cpf')},
        ),
    ]
