# Generated by Django 6.0.1 on 2026-03-01 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_profile_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='lembrete_whatsapp_enviado',
            field=models.BooleanField(default=False),
        ),
    ]
