# Generated by Django 6.0.1 on 2026-03-01 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_consulta_lembrete_whatsapp_enviado'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='reagendamentos_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='status',
            field=models.CharField(choices=[('agendada', 'Agendada'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('finalizada', 'Finalizada'), ('reagendamento_pendente', 'Aguardando Reagendamento')], default='agendada', max_length=25),
        ),
        migrations.CreateModel(
            name='LembreteLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('status_envio', models.CharField(max_length=50)),
                ('mensagem_corpo', models.TextField()),
                ('resposta_paciente', models.TextField(blank=True, null=True)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lembretes', to='home.consulta')),
            ],
        ),
    ]
