# Generated by Django 6.0.1 on 2026-03-03 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_consulta_reagendamentos_count_alter_consulta_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lembretelog',
            options={'ordering': ['-data_envio']},
        ),
        migrations.AddField(
            model_name='clinic',
            name='plano',
            field=models.CharField(choices=[('essential', 'Essential'), ('professional', 'Professional')], default='essential', max_length=20),
        ),
        migrations.AddField(
            model_name='lembretelog',
            name='tipo',
            field=models.CharField(default='Lembrete 24h', max_length=50),
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='assinatura_digital',
            field=models.ImageField(blank=True, null=True, upload_to='assinaturas/'),
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='cro',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='documento_fiscal',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='forma_pagamento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lembretelog',
            name='consulta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_mensagens', to='home.consulta'),
        ),
        migrations.AlterField(
            model_name='lembretelog',
            name='status_envio',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependentes', to='home.paciente'),
        ),
        migrations.CreateModel(
            name='ConfiguracaoWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instancia_nome', models.CharField(help_text='Ex: clinica_odonto_1', max_length=100, unique=True)),
                ('instancia_token', models.CharField(blank=True, max_length=255, null=True)),
                ('apikey_instancia', models.CharField(blank=True, max_length=255, null=True)),
                ('status_conexao', models.CharField(choices=[('connected', 'Conectado'), ('disconnected', 'Desconectado'), ('connecting', 'Conectando...')], default='disconnected', max_length=20)),
                ('lembretes_ativos', models.BooleanField(default=False)),
                ('tipo_envio', models.CharField(choices=[('24h', '24 horas antes'), ('8am', '08:00 da manhã do dia anterior')], default='24h', max_length=20)),
                ('mensagem_confirmacao', models.TextField(default='Olá *{paciente}*, confirmamos sua consulta com Dr(a). {medico} para amanhã, dia {data} às {hora}? Digite SIM para confirmar ou NÃO para cancelar.')),
                ('fidelizacao_ativa', models.BooleanField(default=False)),
                ('mensagem_retorno', models.TextField(default='Olá *{paciente}*, faz 6 meses da sua última consulta. Vamos agendar uma revisão de rotina?')),
                ('permitir_reagendamento_auto', models.BooleanField(default=True)),
                ('clinic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_config', to='home.clinic')),
            ],
        ),
    ]
