# Generated by Django 6.0.1 on 2026-03-04 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_alter_lembretelog_options_clinic_plano_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='home.paciente'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultas_como_responsavel', to='home.paciente'),
        ),
    ]
