# Generated by Django 6.0.1 on 2026-03-06 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_alter_consulta_paciente_alter_consulta_responsavel'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='telefone_limpo',
            field=models.CharField(blank=True, db_index=True, help_text='Apenas números do telefone para busca rápida', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='whatsapp_jid',
            field=models.CharField(blank=True, db_index=True, help_text='ID único do WhatsApp (útil para resolver o problema de IDs @lid)', max_length=100, null=True),
        ),
    ]
