# Generated by Django 6.0.1 on 2026-03-06 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_paciente_telefone_limpo_paciente_whatsapp_jid'),
    ]

    operations = [
        migrations.AddField(
            model_name='lembretelog',
            name='message_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
