# Generated by Django 6.0.1 on 2026-03-13 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_lembretelog_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaowhatsapp',
            name='mensagem_solicitacao_reagendamento',
            field=models.TextField(default='Entendido, *{paciente}*. Recebemos sua solicitação de reagendamento. Em breve nossa equipe entrará em contato para ajustar o melhor horário para você.', help_text='Tags: {paciente}, {clinica}'),
        ),
        migrations.AddField(
            model_name='configuracaowhatsapp',
            name='mensagem_sucesso_confirmacao',
            field=models.TextField(default='Maravilha, *{paciente}*! 🙌\n\nSua consulta está confirmadíssima para {data_hora}.\nEstamos preparando tudo para te receber com muito carinho aqui na *{clinica}*.\n\nTenha um excelente dia! ✨', help_text='Tags: {paciente}, {data_hora}, {clinica}'),
        ),
        migrations.AlterField(
            model_name='configuracaowhatsapp',
            name='mensagem_confirmacao',
            field=models.TextField(default='Olá *{paciente}*, confirmamos sua consulta com Dr(a). {medico} para amanhã, dia {data} às {hora}? Digite SIM para confirmar ou NÃO para cancelar.', help_text='Tags: {paciente}, {medico}, {data}, {hora}, {clinica}'),
        ),
    ]
