# Generated by Django 6.0.1 on 2026-03-13 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_configuracaowhatsapp_mensagem_solicitacao_reagendamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaowhatsapp',
            name='instancia_nome',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, unique=True),
        ),
    ]
