# Generated by Django 6.0.1 on 2026-03-14 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_alter_configuracaowhatsapp_instancia_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracaowhatsapp',
            name='fidelizacao_ativa',
        ),
        migrations.RemoveField(
            model_name='configuracaowhatsapp',
            name='mensagem_retorno',
        ),
        migrations.AddIndex(
            model_name='consulta',
            index=models.Index(fields=['clinic', 'data_hora'], name='home_consul_clinic__909346_idx'),
        ),
        migrations.AddIndex(
            model_name='consulta',
            index=models.Index(fields=['status'], name='home_consul_status_102d3b_idx'),
        ),
    ]
