# Generated by Django 6.0.1 on 2026-03-15 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_remove_configuracaowhatsapp_fidelizacao_ativa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoFidelizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight', models.TextField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('contatado', 'Mensagem Enviada'), ('nao_respondeu', 'Não Respondeu'), ('recusou', 'Recusou / Não quis'), ('agendado', 'Agendou Consulta'), ('ignorar', 'Não sugerir mais')], default='pendente', max_length=20)),
                ('data_analise', models.DateTimeField(auto_now_add=True)),
                ('ultima_interacao', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.clinic')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.paciente')),
            ],
            options={
                'ordering': ['-data_analise'],
            },
        ),
    ]
