# Generated by Django 6.0.1 on 2026-03-16 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_historicofidelizacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicofidelizacao',
            name='categoria',
            field=models.CharField(choices=[('risco', 'Risco'), ('retorno', 'Retorno')], default='retorno', max_length=20),
        ),
    ]
