# Generated by Django 6.0.1 on 2026-03-17 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_historicofidelizacao_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicofidelizacao',
            name='insight_whatsapp',
            field=models.TextField(blank=True, null=True),
        ),
    ]
