# Generated by Django 6.0.1 on 2026-03-17 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_historicofidelizacao_insight_whatsapp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicofidelizacao',
            options={'ordering': ['-data_analise'], 'verbose_name': 'Histórico de Fidelização', 'verbose_name_plural': 'Históricos de Fidelização'},
        ),
        migrations.AlterField(
            model_name='historicofidelizacao',
            name='categoria',
            field=models.CharField(choices=[('risco', 'Risco'), ('alerta', 'Alerta'), ('retorno', 'Retorno')], default='retorno', max_length=20),
        ),
    ]
