# Generated by Django 6.0.1 on 2026-03-18 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_alter_historicofidelizacao_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='clinic',
            name='data_expiracao_teste',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinic',
            name='dono',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='minha_clinica', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
