# Generated by Django 6.0.1 on 2026-03-20 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_clinic_ativo_clinic_data_expiracao_teste_clinic_dono'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='data_ultimo_pagamento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinic',
            name='ultimo_id_pagamento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
