# Generated by Django 6.0.1 on 2026-03-20 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_clinic_data_ultimo_pagamento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArquivoPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='pacientes/prontuarios/%Y/%m/', verbose_name='Arquivo/Exame')),
                ('descricao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='home.paciente')),
            ],
            options={
                'verbose_name': 'Arquivo do Paciente',
                'verbose_name_plural': 'Arquivos dos Pacientes',
                'ordering': ['-data_upload'],
            },
        ),
    ]
