# Generated by Django 6.0.1 on 2026-03-20 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_arquivopaciente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dentista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('cro', models.CharField(blank=True, max_length=20, null=True)),
                ('cor_calendario', models.CharField(default='#3788d8', help_text='Cor para exibir no FullCalendar (Ex: #3788d8)', max_length=7)),
                ('ativo', models.BooleanField(default=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.clinic')),
            ],
        ),
        migrations.AddField(
            model_name='consulta',
            name='dentista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consultas', to='home.dentista'),
        ),
        migrations.CreateModel(
            name='Procedimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('duracao_estimada', models.PositiveIntegerField(default=30, help_text='Duração em minutos')),
                ('valor_sugerido', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('ativo', models.BooleanField(default=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.clinic')),
            ],
        ),
        migrations.AddField(
            model_name='consulta',
            name='procedimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultas', to='home.procedimento'),
        ),
    ]
