# Generated by Django 6.0.1 on 2026-03-21 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_dentista_consulta_dentista_procedimento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='forma_pagamento',
        ),
    ]
