# Generated by Django 6.0.1 on 2026-03-21 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_remove_consulta_forma_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='forma_pagamento',
            field=models.CharField(blank=True, choices=[('', 'Selecione a forma...'), ('pix', 'Pix'), ('dinheiro', 'Dinheiro'), ('cartao_credito', 'Cartão de Crédito'), ('cartao_debito', 'Cartão de Debito'), ('transferencia', 'Transferência Bancária')], max_length=50, null=True),
        ),
    ]
